apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: app-of-apps
    namespace: argocd
spec:
    description: This project is dedicated for App of Apps
    sourceRepos:
      - https://github.com/HarishMatur/ArgoCD.git
    destinations:
      - server: https://kubernetes.default.svc
        namespace: argocd
      - server: https://kubernetes.default.svc
        namespace: app-of-apps

    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
