apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/HarishMatur/ArgoCD.git
              revision: main
              directories:
                - path: multi-cluster/manifests/*

          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - dev
                      - prod
  
  template:
    metadata:
      name: '{{.path.basename}}-{{.name}}'
    
    spec:
      project: multi-cluster

      source:
        repoURL: https://github.com/HarishMatur/ArgoCD.git
        targetRevision: main
        path: '{{.path.path}}'

      destination:
        server: '{{server}}'
        namespace: '{{.path.basename}}-{{index .metadata.labels "environment"}}'


      syncPolicy:

        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true